apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: detsombetyrnoe-next
  namespace: detsombetyrnoe
  labels:
    team: detsombetyrnoe
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /api/isAlive
  readiness:
    path: /api/isAlive
  replicas:
    min: 1
    max: 1
  webproxy: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - host: api.sanity.io
        - host: c9hptfq7.api.sanity.io
        - host: apicdn.sanity.io
        - host: c9hptfq7.apicdn.sanity.io
        - host: cdn.sanity.io
        - host: arbeidsplassen.nav.no
        - host: api.amplitude.com
        - host: api.github.com
  ingresses:
    - https://detsombetyrnoe.no
    - https://www.detsombetyrnoe.no
    - https://detsombetyrnoe.labs.nais.io
  filesFrom:
    - secret: env
      mountPath: /usr/src/secrets
